name: riverpod_boilerplate
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: '>=3.0.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    #Localizations
    intl: ^0.18.1

    #State management
    flutter_riverpod: ^2.3.10
    riverpod_annotation: ^2.1.4

    #Routing
    auto_route: ^7.8.3

    #Responsiveness
    flutter_screenutil: ^5.9.0

    #Permissions
    permission_handler: ^10.4.3

    #HttpClient
    dio: ^5.3.2

    #Storage
    flutter_secure_storage: ^9.0.0
    hive: ^2.2.3
    hive_flutter: ^1.1.0

    #Code generation
    json_annotation: ^4.8.1
    freezed_annotation: ^2.4.1

    #Image
    cached_network_image: ^3.2.3
    flutter_svg: ^2.0.7

    #Logging
    loggy: ^2.0.3
    flutter_loggy_dio: ^3.0.1

    #Connectivity
    connectivity_plus: ^4.0.2

    #Environment
    envied: ^0.3.0+3

    #Loader
    shimmer: ^3.0.0

    #Tools
    cupertino_icons: ^1.0.5
    path_provider: ^2.1.1
    path: ^1.8.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    flutter_lints: ^2.0.2
    custom_lint: ^0.5.3
    riverpod_lint: ^2.0.4
    build_runner: ^2.4.4
    hive_generator: ^2.0.0
    auto_route_generator: ^7.3.1
    json_serializable: ^6.7.1
    freezed: ^2.4.1
    mockito: ^5.4.2
    flutter_gen_runner: ^5.3.1
    envied_generator: ^0.3.0+3
    riverpod_generator: ^2.3.1

flutter_gen:
    output: lib/core/utils/assets_gen/ # Optional (default: lib/gen/)

    integrations:
        flutter_svg: true
        flare_flutter: true
        rive: true

flutter:
    generate: true
    uses-material-design: true

    assets:
        - assets/images/

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Black.ttf
              - asset: assets/fonts/Poppins-Bold.ttf
              - asset: assets/fonts/Poppins-ExtraBold.ttf
              - asset: assets/fonts/Poppins-ExtraLight.ttf
              - asset: assets/fonts/Poppins-Italic.ttf
              - asset: assets/fonts/Poppins-Light.ttf
              - asset: assets/fonts/Poppins-Medium.ttf
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-SemiBold.ttf
              - asset: assets/fonts/Poppins-Thin.ttf

flutter_intl:
    enabled: true
